import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Social App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {

  return (
    <html lang="pt">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
